### ISSUE TITLE
Add a text area for action related to a client

### ISSUE THREAD

**Issue by maximest-pierre** [savoirfairelinux/santropol-feast#109]
There need to be a text area name action added to the model just like the notes class inside the member/models.py.

**Comment by RignonNoel** [comment]
What's the difference between note and action?

**Comment by maximest-pierre** [comment]
A note is a like a text that is a history about a client but an action is something that need an action. Like a client has given a cheque, verify that the billing is right and its attach to the client.

**Comment by RignonNoel** [comment]
And what the process with this new feature?:

1. An employee create a new action
2. A second employee see the action
 1. The second employee set the action to 'read'
 2. The second employee set the action to 'resolve'
 
Can i resolve an action already readed?
Action is set automatically to read if resolve?
Who appear if i set to 'read' but never to 'resolve'?

--- 

Is it relevant to add action? If the user saw a note he should have taken operation if there is one ?
Or also we should upgrade note with a 'resolve' boolean' ?

PS: It's a request of santropol?

**Comment by maximest-pierre** [comment]
Its more along the line of there is something with this client that needs to be verify immediately and action must be taken.

We can upgrade the note with an resolve field and also add a note type.

It was a request of Santropol.

**Comment by RignonNoel** [comment]
> that needs to be verify immediately

Ok, then we may need a field "urgent" to sort note in priority.

> We can upgrade the note with an resolve field and also add a note type.

But for me it's incoherent to have 'read' and 'resolve' on the same object...

 - If we set to 'read' we can't see the note to set to 'resolve'
 - If we set to 'resolve' it's automatically 'read'

So why not just keep the note and add a priority field?
If the note need an action, the 'read' is equal to 'resolve' in my head, as a user.

**Comment by maximest-pierre** [comment]
I think that is the best idea. To add a field that is urgent. It will also be at the top of the notification list.

**Comment by RignonNoel** [comment]
Yes, and you can add some logic and style.

 - Different color to show the 'urgent' label
 - Add popup when we set to 'read' to verify the action is taken. (because urgent = important in lot of case)

**Comment by maximest-pierre** [comment]
That sounds like a good plan.

**Comment by manumilou** [comment]
Adding a field Priority to the Notification model.

Possible values:
- normal
- urgent 

Could be improved.
