### ISSUE TITLE
Create python factories for meals and members models

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#11]
It will be used to:

* Populate automatically the database with coherent data, for development purposes
* Populate automatically the database with coherent data, for testing purposes

**Comment by TempestMia** [comment]
Just a suggestion  :)
1 person goes into the admin and creates a bunch of data, then dumps the data as fixture files that can be added to the repository and loaded by other developers

**Comment by RignonNoel** [comment]
Yeah, it's very smart for integration and validation test. But factories are interessting for unit test to make quickly 'real' data dynamically.

But lot of project and people work just with fixtures.
