### ISSUE TITLE
Configure continuous integration tools

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#12]
The repository should be plugged into Travis CI framework to provide solid continuous integration features, including:

* Code coverage calculation
* Unit / functional tests execution
* PEP8 coding standards validation

**Comment by manumilou** [comment]
@RignonNoel I merged your PR (#13). TravisCI now runs build at each push.

The first build failed though, if you could have a look.

**Comment by RignonNoel** [comment]
Yes, it's ok it's just the PEP8 standard who is break.
We need to make an issue to correct all PEP8 fail.

**Comment by manumilou** [comment]
Tests now passes and the current build is tagged as successful. Thanks @RignonNoel
