### ISSUE TITLE
i18n: use english strings instead of "message ids"

### ISSUE THREAD

**Issue by cormier** [savoirfairelinux/santropol-feast#121]
The project uses "message ids" instead of untranslated strings for messages.  This is neither what is recommended by the gettext documentation nor what we generally see in open source projects. When we look at the gettext documentation of po files [1], we see that the message id *is* the untranslated string, not an abstract id. 

For open source projects, the base language is  generally english. This is what we see in the Django project. [2]

I believe that we should avoid abstract message ids because it complicates the translation process. For these reasons I believe that we should:

1. Replace the abstract message ids with english strings
2. Document this decision in the i18n section of the README

References
[1] https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html#PO-Files
[2] https://github.com/django/django/blob/ecb59cc6579402b68ddfd4499bf30edacf5963be/django/contrib/admindocs/apps.py#L7

**Comment by RignonNoel** [comment]
I'm ok with you, i use english version all time and in all projects.

But if we set directly english version we need to find a good practice for promotional text.
Habitually it's not a good practice to copy-paste the same text in lot of template. We need to store constant of the site (ex : name, welcome_text, address, phone)

**Comment by manumilou** [comment]
@cormier My bad, it was a bad habit from Laravel applications, that do not use gettext anyway. I agree as well with this. We should migrate as soon as possible.

**Comment by RignonNoel** [comment]
@manumilou Ok, and we store promotionnal text in a dict in settings.py ?

**Comment by cormier** [comment]
@manumilou: I didn't know it worked this way in Laravel. Sorry! Saying that it is not what we see in open source projects was a little bit too strong and I should have said "django projects" instead :wink:

@RignonNoel is promotional text just a few constants ? maybe it can reside in the settings

**Comment by RignonNoel** [comment]
@cormier In my projects i put it in my settings.py yes as here : 
https://github.com/CentechMTL/TableauDeBord/blob/master/centech2/settings.py

**Comment by manumilou** [comment]
@cormier no worries ;-) 

@RignonNoel Is this translatable ?

**Comment by RignonNoel** [comment]
Yes you can. Just use the same utils as in view.

**Comment by cormier** [comment]
In the settings we should use lazy translations so that the translation is delayed until an actual request is made

https://docs.djangoproject.com/es/1.9/topics/i18n/translation/#lazy-translations

**Comment by RignonNoel** [comment]
So we are ok to set directly the english version in the code.
I close the issue and invite you to see the #60 if you're interested.
