### ISSUE TITLE
Model for member propose changes

### ISSUE THREAD

**Issue by maximest-pierre** [savoirfairelinux/santropol-feast#127]
At looking at the models I found some places where we could modify to help with the form.

**Comment by maximest-pierre** [comment]
```
class Member(models.Model):

    class Meta:
        verbose_name_plural = _('members')

    # Member information
    firstname = models.CharField(
        max_length=50,
        verbose_name=_('firstname')
    )

    lastname = models.CharField(
        max_length=50,
        verbose_name=_('lastname')
    )

    gender = models.CharField(
        max_length=1,
        choices=(
            ('M', _('male')),
            ('F', _('female')),
            ('U', _('unknown')),
        ),
        default='U'
    )

    birthdate = models.DateField(
        auto_now=False,
        auto_now_add=False,
        default=timezone.now
    )
```
The first changes is to remove the gender and birthday to only the client. We dont need to know the gender or the birthday of a referent or a emergency contact.

**Comment by RignonNoel** [comment]
I understand what you want but here you kill the entity model.

All member have a gender, not just client.
But if you don't need this information for all member, you can just set it optionnal and invite client to set this information.

Tomorrow if we want a new model (volunteer for example) we don't need to set the birthday in volunteer.

**Comment by maximest-pierre** [comment]
I like that idea should i make the change in my pr or another pr. This would be easier to do this in my current pr since it directly affect the wizard form.

**Comment by RignonNoel** [comment]
Normally you need to make a PR on this issue.
