### ISSUE TITLE
In Class Member, "facturation" is not an English word

### ISSUE THREAD

**Issue by lamontfr** [savoirfairelinux/santropol-feast#139]
Since the code and comments must be in English, I suggest replacing "facturation" by "invoicing".

See also issue https://github.com/savoirfairelinux/santropol-feast/issues/110 "Add third party billing to the client model", where I propose changes to the data model.

**Comment by manumilou** [comment]
Agreed!

**Comment by lamontfr** [comment]
I suggest closing this issue. See #161 which proposes a better solution.
