### ISSUE TITLE
Use a native date input for the birthday field

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#142]
In the basic_information step, the birthday field is defined as a DateField. However, it is rendered as a text input, which makes it harder to select a date.

The rendered HTML should be a input type="date".
It could also be three separated fields: year, month, day.

**Comment by fchiggins** [comment]
This is for the Add Client page, which is reached by going to the drop down menu item Client > Add, which links to the page /member/create/basic_info/ with this birthday field. 

This page seems to be generated by /member/forms.py, and the birthday field specifically by this section:
`birthdate = forms.DateField(label=_("Birthday"))`

Here is the documentation for this form field:
https://docs.djangoproject.com/en/1.9/ref/forms/fields/#datefield

There is also the /member/templates/forms/steps/basic_info.html
`<div class="field {% if wizard.form.birthdate.errors %} error {% endif %}">
    <label>{{ wizard.form.birthdate.label }}</label>
    {{ wizard.form.birthdate }}
</div>`

And here is the relevant sections of /member/views.py for the rendering of this template:
`member = Member.objects.create(
            firstname=basic_info.cleaned_data.get('firstname'),
            lastname=basic_info.cleaned_data.get('lastname'),
            gender=basic_info.cleaned_data.get('gender'),
            birthdate=basic_info.cleaned_data.get('birthdate'),
        )
        member.save()`

This is module imported in views.py 
`from formtools.wizard.views import NamedUrlSessionWizardView`





I checked with @manumilou and a couple other people, and the conclusion was that it would be ideal to use a more interactive date choosing interface using jquery or similar. @dkundathagard and I are going to try working on this.
