### ISSUE TITLE
Create link from the client list to the client info view

### ISSUE THREAD

**Issue by maximest-pierre** [savoirfairelinux/santropol-feast#149]
### Expected Behaviour

When a user clicks the name of a person in the client list, it  should redirect them to that client information page.

#### More Information

The url for the client list is: localhost/member/list

The url for the client info view is: localhost/member/view_info/id

The url route is
```
url(_(r'^view_info/(?P<id>\d+)/$'),
                         show_information,
                         name='view_info'),
                         )
```
The id is the primary key id of the client.

**Comment by rjacquemin** [comment]
stat on this

**Comment by dkundathagard** [comment]
I can give this one a try.
