### ISSUE TITLE
Implements a dynamic breadcrumb

### ISSUE THREAD

**Issue by maximest-pierre** [savoirfairelinux/santropol-feast#151]
### Expected Behaviour

The breadcrumb needs to show the current page and also the previous level to get to the current page.
The interactive wireframes show the expected behaviour: 

* https://marvelapp.com/2187ig4#12570954
* https://marvelapp.com/2187ig4

### Actual Behaviour

The breadcrumb is currently hardcoded inside the [breadcrumb template](https://github.com/savoirfairelinux/santropol-feast/blob/dev/django/santropolFeast/santropolFeast/templates/breadcrumb.html).

**Comment by ellmetha** [comment]
Hi! I will start working on this issue ;)
