### ISSUE TITLE
Update menu items in the client tab

### ISSUE THREAD

**Issue by maximest-pierre** [savoirfairelinux/santropol-feast#152]
### Expected Behaviour

The main menu (at the top) should redirect the user to the right section of the application.

Here are the proposed labels for the menu items:

* Client
  * Client List: _member/list_
  * Add Client: _member/create_

### Actual Behaviour

The menu is currently hardcoded inside the base templates, with missing or misconfigured links.

See [base.html](https://github.com/savoirfairelinux/santropol-feast/blob/dev/django/santropolFeast/santropolFeast/templates/base.html)

**Comment by fchiggins** [comment]
I can't replicate the problem. See the attached screenshot for what the dropdown looks like right now:
![client menu screenshot](https://cloud.githubusercontent.com/assets/12721148/15594069/2a629e30-2380-11e6-9e07-5edee98718be.png)

The Search item links to /member/list 
The Add item links to /member/create

Clicking both items successfully goes to the correct page. This is different than what seems to be in the base.html template linked above (in the case of the Add item at least):
`<i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{% url 'member:list' %}" class="item">Search</a>
                    <a href="{% url 'member:member_step' %}" class="item">Add</a>
                </div>`

I get the impression that someone has fixed this already. Maybe the issue just needs to be updated to reflect this?
