### ISSUE TITLE
Implement test for the different models

### ISSUE THREAD

**Issue by maximest-pierre** [savoirfairelinux/santropol-feast#155]
### Expected Behaviour

We need a way to test the different models.

Here are the models that need test:
- Member (There is already some test)
- Meal (not a priority right now)
- Order (not a priority right now)

### Actual Behaviour

There is currently only a couple of test that are being done.

**Comment by manumilou** [comment]
I implemented a couple of sample functional tests in Page model.
Tests on member model should be tackle on issue #153
