### ISSUE TITLE
Status field inside the client form must not be required

### ISSUE THREAD

**Issue by maximest-pierre** [savoirfairelinux/santropol-feast#157]
### Expected Behaviour

On the Allergies step of the client creation form, the **Meal Status** field should be either Active or not, without any validation problems.

### Actual Behaviour

If the **Meal Status** is set to Inactive, the validation blocks and prevents from getting to the next step.

### Steps to reproduce

* Go the client creation form: _member/create_
* Fill out fields until the _Allergies_ step
* On the _Allergies_ step, set the Meal status to Inactive, and click **Next**
* A validation error occurs, specifying that the status field is mandatory

![validation_bug](https://cloud.githubusercontent.com/assets/212768/15588410/c72b85bc-235b-11e6-89d0-892bba38f33f.png)

**Comment by ellmetha** [comment]
Hi! I will start working on this issue ;)
