### ISSUE TITLE
Allow the administrator to edit models from the client view page

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#159]
### Expected Behaviour

From the client view page, every data should be editable.
An edit link, by section, should be present, redirecting to an editing page.
Right now, the editing page could be the admin backend.

See: https://marvelapp.com/2187ig4#12570955

### Actual Behaviour

No way to edit anything, except by going directly to the admin backend.

**Comment by lafe3402** [comment]
Eric Lafontaine will be looking into this with colleagues :)
