### ISSUE TITLE
Define the Order / OrderItems models

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#161]
### Expected Behaviour

An order can contain multiple order items. 

An order item can be billable or not.
An order item can be:

* Meal (billable)
* Visit
* Card
* General Store item (billable)

The billing system must be able to properly compute the amount of an order.

### Actual Behaviour

No orders.

**Comment by lamontfr** [comment]
I want to work on this issue.

**Comment by lamontfr** [comment]
Here is a first proposal for discussion. See comments below the diagram.
![revised_data_model](https://cloud.githubusercontent.com/assets/8512608/15636234/2342be1c-25c6-11e6-9479-6b1aa6b37abe.png)

** Changes made **

- member app models
  - Member now has FK to Address as discussed on HackNight on May 26th
    (was reverse)
  - Client now has FK to Member that will be billed (was pointing to
    billing address)
    - This allows billing a 3rd party, so we can store firstname and
      lastname that are entered in the client wizard
  - in Client, facturation attribute is renamed rate_type to be
    consistent with the client view_info
  - Meal_request is a new class
    - to store the dates (schedule) on which client wants to receive a
      meal
  - Allergy_client is renamed Restriction
    - ex. John Doe does not eat Seafood
  - Client_option is a new many to many table
    - ex. John Doe wants Green salad
    - ex. John Doe wants Purée all preparation
  - moved attributes gender and birthdate from Member to Client,
    because these are not needed for those who are billed nor for
    emergency contacts
  - added attribute emergency_contact_relationship in Client
    - ex. daughter
- meal app models
  - Allergy is renamed Restricted_item
    - ex. Gluten, Seafood, Couscous
  - Ingredient is renamed Component
    - ex. Main dish name, vegetable name, seasonal extra name
  - Allergy_ingredient is renamed Incompatibility
    - ex. Haddock is incompatible with Seafood
  - Meal is renamed Ingredient
    - ex. Haddock, Paprika, Onions
  - Menu_ingredient is renamed Menu_component
    - ex. On 2016-05-30 the main dish is Coq au vin
    - ex. On 2016-05-30 the Vegetable 1 is Potatoes
  - Ingredient_meal is renamed Component_ingredient
    - ex. Coq au vin includes Onions
  - Option is a new class
    - to store the types of side dish (ex. green salad) and
      for preparation (ex. purée)

**Comment by lamontfr** [comment]
@maximest-pierre  I just made the first set of changes to the member models. Please look at branch https://github.com/lamontfr/santropol-feast/tree/fix161a . If you want, you can start to apply the changes to the client wizard and the view-info view and template. Let me know.

**Here are the changes I made** 

  - [X] Member now has FK to Address as discussed on HackNight on May
    26th (was reverse)
  - [X] Client now has FK to Member that will be billed (was pointing
    to billing address)
  - [X] in Client, facturation attribute is renamed rate_type to be
    consistent with the client view_info
  - [X] moved attributes gender and birthdate from Member to Client,
    because these are not needed for those who are billed nor for
    emergency contacts
  - [X] added attribute emergency_contact_relationship in Client

**Comment by maximest-pierre** [comment]
I think that the best way to tackle this issue would be to make a branch on the main repo and work from there. It would be much easier to fix the bugs this way without having to break the dev branch. @manumilou what is your opinion on this matter.

**Comment by maximest-pierre** [comment]
I made a branch for this issue

https://github.com/savoirfairelinux/santropol-feast/tree/feature/django-model-change

**Comment by lamontfr** [comment]
In git bash I see all branches 

$ git checkout upstream/
upstream/database-protype-conception
upstream/dev
upstream/ehtaga_display_logged_user_52
upstream/feature/dashboard-metrics
upstream/feature/dashboard-widget-statistics
upstream/feature/implements-member-notes
upstream/feature/improve-client-creation-form
upstream/feature/member-note-add-priority
upstream/feature/notification-status
upstream/feature/review-django-models
upstream/fix/nullable-fields
upstream/issue-63
upstream/master
upstream/maximest-pierre-FactoryInit
upstream/maximest-pierre-fix_51_implement_form
upstream/TempestMia-client-model-list-view

but I cannot see

https://github.com/savoirfairelinux/santropol-feast/tree/feature/django-model-change

Any suggestion ?

**Comment by manumilou** [comment]
Try: git branch -a

Le 30 mai 2016 12:35:14 HAE, Francois Lamontagne <notifications@github.com> a écrit :
>In git bash I see all branches 
>
>$ git checkout upstream/
>upstream/database-protype-conception
>upstream/dev
>upstream/ehtaga_display_logged_user_52
>upstream/feature/dashboard-metrics
>upstream/feature/dashboard-widget-statistics
>upstream/feature/implements-member-notes
>upstream/feature/improve-client-creation-form
>upstream/feature/member-note-add-priority
>upstream/feature/notification-status
>upstream/feature/review-django-models
>upstream/fix/nullable-fields
>upstream/issue-63
>upstream/master
>upstream/maximest-pierre-FactoryInit
>upstream/maximest-pierre-fix_51_implement_form
>upstream/TempestMia-client-model-list-view
>
>but I cannot see
>
>https://github.com/savoirfairelinux/santropol-feast/tree/feature/django-model-change
>
>Any suggestion ?
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/savoirfairelinux/santropol-feast/issues/161#issuecomment-222525233

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by lamontfr** [comment]
i tried, and see my origin branches plus the all upstream branches except "feature/django-model-change".

My question is : I think I must fork "feature/django-model-change" to do my work, then submit PRs that are meant to go into it, is that right ?

**Comment by manumilou** [comment]
@lamontfr 

Did you update your repo? 

```
git fetch
```

It will update existing references and fetch new ones.

**Comment by lamontfr** [comment]
@manumilou Thanks Manu, You are right, I had forgotten the fetch.

**Comment by manumilou** [comment]
@lamontfr Can you push your changes on models ? We need them to update views.

**Comment by lamontfr** [comment]
@manumilou I am almost done. I will submit a PR soon.

**Comment by lamontfr** [comment]
@manumilou @maximest-pierre The complete models are in branch https://github.com/lamontfr/santropol-feast/tree/fix161b This passes "python manage.py check". I closed pull request 183. I simplified the Data Model too. See below.

![revised_data_model](https://cloud.githubusercontent.com/assets/8512608/15709629/b8bab4d6-27d3-11e6-8e5a-177679f58b53.png)

**Comment by manumilou** [comment]
As discussed with @maximest-pierre , here is a few points:

- The **delivery status** of a client is missing: Ongoing / Episodic. Should be a property of a Client. 
- The **Order** table should contain all expected deliveries at the moment the kitchen count process is triggered. Orders could also be generated in advance, or for a given date.

On how saving the delivery preferences (at least the date for now):

There is a table called _Meal Request_, that, I guess, is supposed to serve this purpose. But we have been thinking to something better: 

- **Episodic clients:** a client calls Santropol because he wants to be delivered a meal on July 25th. An order is then created for him in the Order table at this given date, with a proper status.

- **Ongoing clients**: a client wants to be delivered on monday, wednesday and friday. every week. We need a way to modelize this. @maximest-pierre is working on that. Could be a json-encoded string or a Many-to-Many table for instance.

Any comments ?

**Comment by lamontfr** [comment]
I will get back to you before 14h30.

**Comment by maximest-pierre** [comment]
I made two pr #184  and #185. The 184 is ready to merge it adds a char field that contains episodic or ongoing. The other pull request (WIP) is a many to many field that represents which day of the week the client receive an order. We can still change it.

**Comment by manumilou** [comment]
I merged #184

**Comment by lamontfr** [comment]
@manumilou @maximest-pierre Here are my comments on your points earlier today. 

- The **delivery status** of a client is missing: Ongoing /  Episodic. Should be a property of a Client.
  - Reply : I agree with PR 184.

- The **Order** table should contain all expected deliveries at the
  moment the kitchen count process is triggered. Orders could also be
  generated in advance, or for a given date.
  - Reply part 1 : Table **Order** already has the delivery_date (which can be in
    the future) and also the status. I will add a creation_date
    property to keep the date on which the "planned meal delivery" is
    generated for ongoing clients or when the customer manager
    creates an entry for an episodic client to receive a meal for a specific date.
  - Reply part 2 : Table **Meal_request** is not needed any more, I will remove
    it.

- On how to save the delivery preferences (at least the date for now):
  - Reply : Table **Option** and Many to many table **Client_option** can be
    uses to keep **all** client preferences, because we want the system to
    be as generic as possible (not Santropol Roulant specific). So we
    can add an Option_group_choice "weekly schedule" and have one
    record in option for each day of the week. The Client_option(s)
    sets the day(s) for a given client. We can then generate orders a
    (few) weeks ahead of time by "joining" on this information. This avoids
    creating a specific many to many relationship.

I am available to discuss it. You can call me between now and 15h30. Maxime has my cell number.
