### ISSUE TITLE
Associate a route when generating clients

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#214]
The client generation uses FactoryBoy library, to randomly generates model instances.

To generate clients, run:

`django/santropolFeast/python manage.py createclients`

It will create a 10 clients batch.

### Expected Behaviour

* The created clients must be assigned to a route (Member.Model.Route)

### Actual Behaviour

* No route is assigned to the created clients

### Steps to reproduce

* Load the route: `python manage.py loaddata routes`
* Create the clients: `python manage.py createclients`
* Go to the /member/list and check that the route is **None** for every clients

**Comment by ssirois** [comment]
I'll take this for tonight.
