### ISSUE TITLE
Get all the birthday boys and girls of the day

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#217]
### Expected Behaviour

A function should returns all the client birthdays of the day.
The dashboard should provide a block that lists the clients birthdays of the day. 
The client model has a _birthdate_ attribute.

### Actual Behaviour

Fake data is displayed in the dashboard block.

### Steps to reproduce

* Go the front page
* See that a lot a clients are displayed in the Birthdays block

**Comment by manumilou** [comment]
Birthdays block: https://github.com/savoirfairelinux/santropol-feast/blob/dev/django/santropolFeast/member/templates/client/birthdays.html

**Comment by cormier** [comment]
I will try making progress on this
