### ISSUE TITLE
The search bar in the main menu is not functional

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#218]
### Expected Behaviour

If I enter a client name in the search bar from the main menu (left side of the page), I should be redirected to the client list page, filtered with my search, using the GET parameters.

Example: http://localhost:8000/member/list/?name=Doe

### Actual Behaviour

The search bar does nothing.

### Steps to reproduce

* Type a name in the search bar
* Try to trigger a search

**Comment by cormier** [comment]
I will try making progress on this
