### ISSUE TITLE
The client list name filter should allow spaces

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#219]
### Expected Behaviour

If I enter a space in my search in the name filter, let's say between a firstname and name, the search does not return anything. But if I search for the name only or the firstname only, it works.

Exemple: I have a client named John Doe.

If I search:

- John: OK
- Doe: OK
- John Doe: OK

### Actual Behaviour

Exemple: I have a client named John Doe.

If I search:

- John: OK
- Doe: OK
- John Doe: NOT OK

### Steps to reproduce

* Generate clients: `python manage.py createclients`
* Go to http://localhost:8000/member/list/
* Test the Name filter

**Comment by cormier** [comment]
I will try to make progress on this one
