### ISSUE TITLE
All client filters should have an empty value

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#220]
### Expected Behaviour

On the [client list](http://localhost:8000/member/list/) page, the **status** and **delivery_type** filters should have an empty value.
On the [order list](http://localhost:8000/order/list/) page, the **status**  filter should have an empty value.

### Actual Behaviour

Once a search has been done, the only way to reset a filter is to click the reset button, thus resetting all filters.

### Steps to reproduce

* Go to the [client list](http://localhost:8000/member/list/) 
* Search for a name
* Try to search for a client, across all status, without resetting the entire form

**Comment by cormier** [comment]
I will try working on this one
