### ISSUE TITLE
Bug in travis.yml : overall test coverage calculation is wrong

### ISSUE THREAD

**Issue by lamontfr** [savoirfairelinux/santropol-feast#234]
### Expected Behaviour

Coverage should include the tests results for **all** apps : member, meal, order, notification, delivery

### Actual Behaviour

Coverage only includes the test result of the last run (currently : notification)

### Proposed fix.

The data file is cleared with each new run, but it should be cumulative. See explanation
https://coverage.readthedocs.io/en/coverage-4.1/cmd.html#data-file

Solution (a) : add -a flag on each coverage line except the first one 

```
coverage run --omit=*.virtualenvs*,*virtualenv* manage.py test --settings=santropolFeast.settings_test member
coverage run --omit=*.virtualenvs*,*virtualenv* -a manage.py test --settings=santropolFeast.settings_test meal
coverage run --omit=*.virtualenvs*,*virtualenv* -a manage.py test --settings=santropolFeast.settings_test order
coverage run --omit=*.virtualenvs*,*virtualenv* -a manage.py test --settings=santropolFeast.settings_test notification
coverage run --omit=*.virtualenvs*,*virtualenv* -a manage.py test --settings=santropolFeast.settings_test delivery
```

Solution (b) : combine all apps in one line

```
coverage run --omit=*.virtualenvs*,*virtualenv*  manage.py test --settings=santropolFeast.settings_test member meal order notification delivery
```

**Comment by maximest-pierre** [comment]
I think solution **b** might be the better one. It is also the cleanest.

**Comment by lamontfr** [comment]
I agree. I will submit a PR for solution (b).

**Comment by lamontfr** [comment]
Fixed by PR https://github.com/savoirfairelinux/santropol-feast/pull/235
