### ISSUE TITLE
Add an order creation form

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#239]
Some work has already be done on the **factory-boy/orders** branch. Please base your work on top of this branch.

### Expected Behaviour

- [ ] Provide a form to create an order
- [ ] Must include a sub-form to add all sort of order items tot the order
- [ ] This sub form must be reusable to be displayed from the order view (could be displayed in a modal window, SemanticUi supports it)
- [ ] A factory must be implemented, to easily create batch of orders, for development and testing purposes
- [x] A command can also be implemented: ` python manage.py createorders` (see **createclients**, which is already implemented)
- [ ] The form and the view must be tested

### Actual Behaviour

* Only the Django backend allow order creation

**Comment by erozqba** [comment]
Hi @manumilou, I can work on this but there are some functionalities already done in the pull request #258, once the pull request is accepted it will be easier to make a rebase of the branch factory-boy/orders over dev and continue to work in the form, view, and test.

**Comment by manumilou** [comment]
Ready to rebase
