### ISSUE TITLE
Show client meal default for the week on client view

### ISSUE THREAD

**Issue by maximest-pierre** [savoirfairelinux/santropol-feast#244]
### Expected Behaviour
Show the meal default for the week on client view.

### Actual Behaviour

There is currently no information that is shown.

**Comment by manumilou** [comment]
Done for the ongoing clients.
Remains to be done for the episodic clients.

**Comment by manumilou** [comment]
Actually the behaviour is identical for ongoing and episodic clients.

**Comment by manumilou** [comment]
![capture d ecran de 2016-08-01 12-24-46](https://cloud.githubusercontent.com/assets/212768/17301030/04eacd34-57e3-11e6-9981-5f1582b8aeaf.png)
