### ISSUE TITLE
Add model menu

### ISSUE THREAD

**Issue by RignonNoel** [savoirfairelinux/santropol-feast#25]
We need a model for menu, to schedule meals of the year.

**It concerns only the main dish. Side dishes and salads are not included.**

## Fields

 - Date
 - Ingredients (of the main dish)

**Comment by RignonNoel** [comment]
We need an other field named 'name_of_meal' to be readable by human when the admin want list menu and control.

**Comment by manumilou** [comment]
Here is how I see the menu creation interface:

- The admin picks a date, or several dates
- The admin can select a meal already created, in a list or an autocomplete
- The meal's ingredients are automatically loaded, and editable by the admin
- On save, the menu, the date(s) and the ingredients, after modification (or not), are saved to the database

What do you think?

**Comment by RignonNoel** [comment]
It's look like perfect for me.

**Comment by RignonNoel** [comment]
@duckish work on it
