### ISSUE TITLE
Be able to add / edit / delete order items from the order view

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#262]
### Expected Behaviour

* From the order view, I can add a new order item. A form must be displayed in a popup.
* From the order view, I can delete delete an order item
* From the order view, I can edit an order item

### Actual Behaviour

Have to use Django admin, which is not very simple due to object relations.

**Comment by erozqba** [comment]
This order will be deleted and all the info will be lost, are you sure?
