### ISSUE TITLE
Bug with local build

### ISSUE THREAD

**Issue by maximest-pierre** [savoirfairelinux/santropol-feast#267]
### Expected Behaviour

The test are suppose to pass on the local machine and on the build server.

### Actual Behaviour

The test are passing on the build server but not on the local machine

See output:

======================================================================
FAIL: test_form_validate_data (member.tests.FormTestCase)
Test all the step of the form with and without wrong data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/django/santropolFeast/member/tests.py", line 932, in test_form_validate_data
    self._test_referent_information_without_errors()
  File "/code/django/santropolFeast/member/tests.py", line 1140, in _test_referent_information_without_errors
    self.assertTrue(b'Required information' not in response.content)
AssertionError: False is not true

----------------------------------------------------------------------
@rjacquemin is also having a build problem with this test.

**Comment by manumilou** [comment]
The problem is related to the different way MySQL and SQLite handle internal autoincrement counter.
