### ISSUE TITLE
No phone number or contact information are attached to generated clients

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#273]
### Expected Behaviour

When using _createclients_ command, a phone number should be present in the client lists (cards). 

### Actual Behaviour

Phone number is empty.

![capture d ecran de 2016-07-28 11-34-51](https://cloud.githubusercontent.com/assets/212768/17218898/5a0d38b2-54b7-11e6-8bf9-544d31072f43.png)

### Steps to reproduce

* Run the command `python manage.py createclients`
* Go to the client list
* See that the phone number is empty

**Comment by maximest-pierre** [comment]
I think that the problem is that the ContactFactory is never called. I am going to work on it later this weekend.
