### ISSUE TITLE
Add type of facturation on member

### ISSUE THREAD

**Issue by RignonNoel** [savoirfairelinux/santropol-feast#29]
When a client is add on the system, he may pay different prices.

## Task

 - Add CharField-Choice on client

## Choices

 - Defaults
 - Low income
 - Solidary

**Comment by adasilva** [comment]
Ashley is work on this.

**Comment by adasilva** [comment]
sent pull request

**Comment by adasilva** [comment]
I am going to make a new pull request. After I run makemigrations, is there another file that needs to be added to the commit besides the models.py?

**Comment by RignonNoel** [comment]
makemigrations create a file in the ```migrations``` directory of your application (here ```member/migrations```). You just need to commit this file, the ```models.py``` won't be updated by this command.

Feel free to ask if you need more details :)
