### ISSUE TITLE
Add a Delivery Notes field to the client Model

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#307]
### Expected Behaviour

* I should be able to a add a **Delivery Notes** text field in the client creation form
* The field widget should be a textarea
* The delivery notes should be displayed in the client view
* The delivery notes should be displayed in the route sheets

### Actual Behaviour

No way to specify any delivery indications.

**Comment by maximest-pierre** [comment]
Should the field be required or optional.

**Comment by manumilou** [comment]
@maximest-pierre Optional
