### ISSUE TITLE
Configure workflow

### ISSUE THREAD

**Issue by RignonNoel** [savoirfairelinux/santropol-feast#39]
- create a branch dev
- link https://waffle.io/savoirfairelinux/santropol-feast in the readme
- forbid force push on master
- forbid PR on master without CI check

**Comment by RignonNoel** [comment]
@manumilou  I can't forbid force push and condition merge on master. 

I've created the dev branch. All PR need to be merge in this branch now. So you can set the dev branch as default branch.

All that can be set in the setting of the repository.

**Comment by manumilou** [comment]
Done.

**Comment by RignonNoel** [comment]
Thx!
