### ISSUE TITLE
Providing multilingual support

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#5]

**Comment by ygotame** [comment]
Durant la création du projet, on a pris en considération la possibilité d'utiliser d'autres langues.

**Comment by manumilou** [comment]
* Built-in in Django
* Make sure that every label is translatable
* Language detection according to the browser for system users 
* i18n + l10n

**Comment by manumilou** [comment]
With @duckish

**Comment by RignonNoel** [comment]
Look this page : https://docs.djangoproject.com/fr/1.8/topics/i18n/translation/
