### ISSUE TITLE
Generate developer documentation from docstring with Sphinx

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#50]
The user documentation (manual) should be written with [Sphinx](http://www.sphinx-doc.org/en/stable/) and hosted on ReadTheDocs.org.

**Comment by discardthree** [comment]
I'm no pro but I've just started incorporating Sphinx into my own projects and I'd like to be on 'team documentation' for the hacknight tonight. :)

**Comment by manumilou** [comment]
@discardthree  :+1:

**Comment by manumilou** [comment]
There is not much documentation yet though, but having the basis structure could be nice!

**Comment by manumilou** [comment]
Related PR: #76
