### ISSUE TITLE
Implement form views and templates composing the multistep client creation form

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#51]
The multistep form is composed of 5 steps:

- [x] Client information
- [x] Referent information (ie the person who referred the client, usually a doctor)
- [x] Client address
- [x] Payment info (NO CREDIT CARD NUMBER)
- [x] Allergies informations
- [x] Food restrictions

Each form can be build independantly, in separate views.

**Comment by manumilou** [comment]
Wireframe for the client information step
![editclientclient](https://cloud.githubusercontent.com/assets/212768/14721853/bc795de2-07d6-11e6-827e-8ecd0cef2767.png)
![detailclientclient](https://cloud.githubusercontent.com/assets/212768/14721854/bc7a3f82-07d6-11e6-8163-96e44402fd3f.png)

**Comment by manumilou** [comment]
Wireframe for the address step:

![ajoutclientadresse](https://cloud.githubusercontent.com/assets/212768/14721861/c888ef12-07d6-11e6-973e-ab0b7ae6fbdb.png)

**Comment by manumilou** [comment]
Wireframe for the restrictions
![detailclientrestrictions](https://cloud.githubusercontent.com/assets/212768/14721866/d61985f6-07d6-11e6-8763-58e2b4df61a2.png)
 step:

**Comment by cormier** [comment]
i will try to do some progress on this !

**Comment by RignonNoel** [comment]
I've speak with the Montreal django meetup, and we don't find a wizzard form or equivalent for Django 1.9 (last version supported = 1.7)

I think we need to rethink the process of creation.

We can add a function on the member model to control the validation of the member. (control the existence of each object attach to the member to be valid)

We create all createview, for all form and redirect each form to the next step/form.

If the user quit the wizzard during the process, the member is not validated (control with the function), and he can continue the creation an other day.

If the user want, he can find the member in the list of member (in a new status for example) and delete the temporary member.

This solution make a security if we delete an attach object who cannot be null. Or we can add a boolean to set the member as 'validated' and the user cannot be 'unvalidated' after.

Thank to has read my perfect english!!

**Comment by manumilou** [comment]
The formtools contrib app has been moved to a separate package.
The new form-tools package to use is here: https://github.com/django/django-formtools/.
Thanks @cormier

**Comment by maximest-pierre** [comment]
A little update, I got a rough skeleton of the form running but its not yet saving data.

**Comment by manumilou** [comment]
https://github.com/savoirfairelinux/santropol-feast/pull/136 is also related.
