### ISSUE TITLE
Display the logged-in user profile information in the header

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#52]
The base template currently hardcodes a fake user name in the header, once logged-in.
It should use the real logged-in user name.

The base template is here: https://github.com/savoirfairelinux/santropol-feast/blob/dev/django/santropolFeast/santropolFeast/templates/base.html

**Comment by manumilou** [comment]
Screenshot 

![feast_header](https://cloud.githubusercontent.com/assets/212768/14722244/9dc4d23a-07d8-11e6-9b7a-3917225874e0.png)

**Comment by adasilva** [comment]
Ashley is working on this.

**Comment by manumilou** [comment]
@Ehtaga I renamed the issue to include your work regarding the user profile information
