### ISSUE TITLE
Define a default url / route

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#55]
Right now, the homepage returns a 404 code, because no route is configured for /

The current homepage is at: http://localhost:8000/p/home.
This page should be the default homepage, when accessing http://localhost:8000.

**Comment by manumilou** [comment]
![404](https://cloud.githubusercontent.com/assets/212768/14722930/4b9ad1e0-07dc-11e6-9fdd-4e9cb6090811.png)

**Comment by francoiseprovencher** [comment]
Mia and I are working on this 😄

**Comment by francoiseprovencher** [comment]
We're done! The PR is incoming

**Comment by manumilou** [comment]
Thank you @francoiseprovencher @TempestMia
