### ISSUE TITLE
Redirect users already logged in

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#56]
If I am already logged-in, and access again the login page: http://localhost:8000/p/login, I should be redirected to the homepage.

Current behaviour: I stay on the login page, with the message _Connecté_ affiché.

![loggedin](https://cloud.githubusercontent.com/assets/212768/14722999/bda0259c-07dc-11e6-9481-2c4c938000cd.png)

**Comment by adasilva** [comment]
Ashley is working on this.
