### ISSUE TITLE
Make the logout button actually log out the user

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#57]
When logged-in, in the header, clicking on the avatar component pops up a Logout button, which does nothing.

It should redirect to http://localhost:8000/p/logout, to actually log me out.

The dropdown is build as a Semantic UI module: http://semantic-ui.com/modules/dropdown.html.

![logout](https://cloud.githubusercontent.com/assets/212768/14723202/da4e1fb8-07dd-11e6-868d-c9f84a4ee4e4.png)

**Comment by cormier** [comment]
@joaoalf is working on this
