### ISSUE TITLE
Some client fields should not be required

### ISSUE THREAD

**Issue by francoiseprovencher** [savoirfairelinux/santropol-feast#63]
When I create a client, some fields should be optional (not required), like:

- Apartment
- Floor
- Restriction
- Allergy

A stakeholder might want to confirm this, but we felt it was weird to be forced to enter those fields if a client might not have an allergy, apartment number, etc.

**Comment by maximest-pierre** [comment]
Yes, this is a good idea. You can go ahead with this issues.

**Comment by manumilou** [comment]
The database structure must then be adapted as the columns _floor_ and _apartment_ require a value.

**Comment by maximest-pierre** [comment]
Should we open an another issues to modified the database structure.

**Comment by manumilou** [comment]
The PR that fixes it : https://github.com/savoirfairelinux/santropol-feast/pull/115
