### ISSUE TITLE
Add alert information on client

### ISSUE THREAD

**Issue by ygotame** [savoirfairelinux/santropol-feast#66]
We need a field to inform volunteer about a problem with a client (can't speak, blinded, cant' walk and more...)

**Comment by TempestMia** [comment]
@ygotame What if a person is both blind and can't walk? Maybe there should be a disabilities ManyToMany

**Comment by RignonNoel** [comment]
@TempestMia This field is more a TextField to look like a notepad.
Any interesting information will be marked just here to have a good visibility.

**Comment by manumilou** [comment]
We want to keep this simple, it will be just a simple textfield attached to the client model.

**Comment by ygotame** [comment]
As asked, @maximest-pierre you can finish the issue
Thank's

**Comment by maximest-pierre** [comment]
@ygotame  thanks, I will work on it tomorrow.
