### ISSUE TITLE
Size consistency

### ISSUE THREAD

**Issue by JulieSFL** [savoirfairelinux/santropol-feast#72]
I found sizes in two models: meal and order.
Sizes in meal are: regular, large
In order: half, regular, double

Does it need to be harmonized?

**Comment by manumilou** [comment]
Yes, it needs to be harmonized. 

The two sizes we want to use are:

* Large
* Regular

**Comment by RignonNoel** [comment]
It's ok, but we need to set this information in one place only.

In meal it's not consistent because it's generic between all user.
In order it's too large because we can order a meal regular and a double

I think we need to set this in a 'order item'.

**Comment by maximest-pierre** [comment]
There is also half portions.

**Comment by RignonNoel** [comment]
@maximest-pierre You're sure?

**Comment by maximest-pierre** [comment]
i am not a 100% sure but I remember hearing people sometimes take half portions. We can confirm with Katrina.

**Comment by RignonNoel** [comment]
Manu can probably say that. He work on the actual DB at Santropol so he can read data (if it's not hardcode)

**Comment by manumilou** [comment]
Half is not used anymore. Pretty sure.
