### ISSUE TITLE
Building an architecture schema

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/santropol-feast#8]
## Objectives

- Define objects, and relations between them
- Define database structure
- Plan for a migration path

Must be done first, discussed and approved with the team.

**Comment by manumilou** [comment]
![diag_relations_obj](https://cloud.githubusercontent.com/assets/212768/14720777/13d3eb58-07d1-11e6-8bcc-e0f08e47971b.jpg)

**Comment by manumilou** [comment]
![diag_ingredients](https://cloud.githubusercontent.com/assets/212768/14720792/2636d634-07d1-11e6-9599-e0992e8158d0.jpg)

**Comment by RignonNoel** [comment]
For me this issue is done and we work on other issues.
Ok to close it ?
