### ISSUE TITLE
Change license to AGPL

### ISSUE THREAD

**Issue by maximest-pierre** [savoirfairelinux/santropol-feast#83]

**Comment by RignonNoel** [comment]
Yeah, we can find the license here : http://choosealicense.com/licenses/agpl-3.0/

> Note: The Free Software Foundation recommends taking the additional step of adding a boilerplate notice to the top of each file. The boilerplate can be found at the end of the license. 

We can also add a little comment on each file, it's a good practice but we need to update after.
