### ISSUE TITLE
URGENT! Changing the set price for "Default " rate type (also listed as billing type)

### ISSUE THREAD

**Issue by JeanFrancoisFournier** [savoirfairelinux/santropol-feast#839]
URGENT!

### Expected Behaviour

We use 2 "billing type/Rate type": Low Income and Default

Both prices are hard coded in the application. 

LOW INCOME: 4,50$ per meal (including a free side dish) with 0,75$ for any extra side dishes or larger portions of the main meal.

DEFAULT: 5,50$ per meal (including a free side dish) with 1,00$ for any extra side dishes or larger portions of the main meal.

In January we will have a price increase of 1$ that will ONLY affect the DEFAULT rate. 

We need to change the value allocated to this DEFAULT rate to 6,00$

### Actual Behaviour

Right now, the value of the DEFAULT rate is set to 5,50$ and can't be changed from the UI or the ADMIN.

**Comment by taowa** [comment]
We can change this: https://github.com/savoirfairelinux/sous-chef/blob/396f86d696fd1dc541b6556dacea8a621e2b7420/src/order/models.py#L57

However, I'm unsure whether this will affect the billing of previous orders.
