### ISSUE TITLE
Add validation and error display on the login form

### ISSUE THREAD

**Issue by maximest-pierre** [savoirfairelinux/santropol-feast#84]

**Comment by manumilou** [comment]
## Validation

No form validation is issued right now on the login form. We should have the following:

- Required fields
- Valid username
- Valid authentification

**Security measure**: The error message must not identify which fields from the username and the password is wrong. It should only state that authentication has failed.

The validation must be done at server level, and could also be done on the frontend side. Please read [this](http://semantic-ui.com/behaviors/form.html) for form validation with Semantic UI.

**Comment by maximest-pierre** [comment]
We should do it all server side just to be more secure but we can do the required fields client side.
