### ISSUE TITLE
Client drop-list in Place orders should only display ACTIVE clients

### ISSUE THREAD

**Issue by JeanFrancoisFournier** [savoirfairelinux/santropol-feast#846]
### Expected Behaviour

Drop-down list should only display active clients in order generation UI form, thus preventing user from creating an order for a paused, stopped or deceased clients.

### Actual Behaviour

The list shows all clients regardless of status. This may cause mistakes when a PAUSED client calls and places an order. If the user doesn't check their status manually, they still can find them in the drop-list and create the order but the kitchen count won't take that order into account since only orders for active clients are processed by the kitchen count.

### Steps to reproduce
* From main menu, Click Orders in left tab
* Click New Orders button
* Client drop-list displays Paused, Stop/Contact, Stop/NoContact and Deceased clients.

**Comment by guillaumep** [comment]
Look in the client query in `src/order/forms.py`:

```
        queryset=Client.objects.all().select_related(
            'member'
        ).only(
            'member__firstname',
            'member__lastname'
        )
```

The query should get active clients only.

**Comment by guillaumep** [comment]
Confirmed working in staging environment: no paused nor pending nor deceased clients are listed.

**Comment by JeanFrancoisFournier** [comment]
Tested on staging with real numbers and fix is confirmed! Also faster to load which is a plus!
