### ISSUE TITLE
Billings should be displayed in descending year, month order

### ISSUE THREAD

**Issue by JeanFrancoisFournier** [savoirfairelinux/santropol-feast#849]
### Expected Behaviour

Billings should be displayed in descending year, month order

### Actual Behaviour

Billings are displayed by ascending years, then by descending months.

### Steps to reproduce

* click BILLING in the left main menu

**Comment by guillaumep** [comment]
<strike>In `src/billing/views.py`, add an `order_by` in `BillingList.get_queryset` (on `uf.qs`).</strike>

**Comment by guillaumep** [comment]
Confirmed working in staging environment.

**Comment by JeanFrancoisFournier** [comment]
tested both the UI visualisation and the creation of billings. Both work great!
